### ISSUE TITLE
Project team assignment with Kanban

### ISSUE THREAD

**Issue by Reem-lab** [Yothu/catalog-of-my-things#47]
## Set Up the project with Kanban board 👍 💯
[Link of the project ](https://github.com/Yothu/catalog-of-my-things/projects/1)
- We are four people.
- Team member 1  is @Reem-lab.
- Team member 2 is @fherrerao.
- Team member 3 is @Yothu.
- Team member 4 is @JEFFKAY16 .

**Comment by DeliceLydia** [comment]
## Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
# Congratulations! 🎉 



### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
